export const testData = [
  // {
  //   additionalInfo: "Must use the Autosled APP/BOL to get paid",
  //   availableDate: "2025-02-11T00:00:00",
  //   createdDate: "2025-02-11T10:11:18Z",
  //   destination: {
  //     city: "LANDOVER",
  //     geoCode: {
  //       latitude: 38.92274,
  //       longitude: -76.887691,
  //     },
  //     metroArea: "Washington - Arlington - Alexandria",
  //     state: "MD",
  //     zip: "20785",
  //   },
  //   digitalOffersEnabled: false,
  //   distance: 151,
  //   expirationDate: "2025-03-13T07:00:00Z",
  //   hasInOpVehicle: false,
  //   hasPublicMarketplace: true,
  //   id: 116444303,
  //   isAutoAcceptEnabled: false,
  //   isBlocked: false,
  //   isPreferred: false,
  //   listingStatus: "LISTED",
  //   name: "defffasdasd",
  //   origin: {
  //     city: "Petersburg",
  //     geoCode: {
  //       latitude: 37.117515,
  //       longitude: -77.405858,
  //     },
  //     metroArea: "Richmond",
  //     state: "VA",
  //     zip: "23805",
  //   },
  //   preDispatchNotes: "",
  //   price: {
  //     balance: {
  //       amount: 110,
  //       balancePaymentMethod: "COMPANY_CHECK",
  //       balancePaymentTermsBeginOn: "RECEIVING_SIGNED_BOL",
  //       paymentTime: "TWO_BUSINESS_DAYS",
  //     },
  //     cod: {
  //       amount: 0,
  //       paymentLocation: "DELIVERY",
  //       paymentMethod: "CASH_CERTIFIED_FUNDS",
  //     },
  //     total: 110,
  //   },
  //   shipper: {
  //     companyName: "carsarrive",
  //     customerId: "8e86c020-3f31-4948-820d-db8b8bc7123a",
  //     email: "transport@autosled.com",
  //     hoursOfOperation: "24/7",
  //     hqTimeZone: "EST",
  //     numberOfRatings: 492,
  //     overallRating: {
  //       averageRating: 5,
  //       totalAmount: 1,
  //     },
  //     phone: "(240) 880-2702",
  //     phoneNumbers: [
  //       {
  //         extension: "",
  //         phoneNumber: "(240) 880-2702",
  //         type: "BILLING",
  //       },
  //       {
  //         extension: "",
  //         phoneNumber: "2408802702",
  //         type: "LISTING",
  //       },
  //       {
  //         extension: "",
  //         phoneNumber: "2408802702",
  //         type: "LOCAL",
  //       },
  //     ],
  //     rating: 99.8,
  //     tierGroup: "Broker",
  //   },
  //   shipperOrderId: "05d88e0c",
  //   sortingDate: {},
  //   trailerType: "OPEN",
  //   vehicles: [
  //     {
  //       additionalInfo: "",
  //       color: "KBZ",
  //       externalVehicleId: "",
  //       id: "183874142",
  //       make: "NISSAN",
  //       model: "Sentra",
  //       qty: 1,
  //       shippingSpecs: {
  //         height: 57,
  //         length: 183,
  //         weight: 3084,
  //         width: 72,
  //       },
  //       vehicleType: "CAR",
  //       wideLoad: false,
  //       year: 2025,
  //     },
  //   ],
  //   website: "central",
  // },
  // {
  //   comments: "",
  //   createdDate: "2025-02-11T10:12:23.950Z",
  //   destinationCity: "Ponca",
  //   destinationState: "NE",
  //   hasBidsAvailable: false,
  //   hasEnclosedTrailer: false,
  //   hasInopVehicle: false,
  //   id: "20302800",
  //   mileage: "942",
  //   name: "deff",
  //   numberOfCars: "2",
  //   originCity: "Mercer",
  //   originState: "PA",
  //   photoURL: "",
  //   pricePerMile: "$1.05",
  //   pricePerShipment: "$985",
  //   sortingDate: {},
  //   viewLink:
  //     "/tab/Transport/ViewLoadShort.asp?nload_id=20302800&npickup_code=",
  //   website: "carsarrive",
  //   yearMakeModel: "2012 Chevrolet Silverado 1500",
  // },
  // {
  //   location: {
  //     pickup: {
  //       distances: [
  //         {
  //           postCode: "08809",
  //           distance: "56",
  //           type: "pickup",
  //           id: "pickup-1739544976167",
  //           filterType: "distances",
  //         },
  //       ],
  //       states: [],
  //     },
  //     delivery: {
  //       distances: [],
  //       states: [
  //         {
  //           type: "delivery",
  //           filterType: "states",
  //           value: "MD",
  //           description: "maryland",
  //           id: "MD-delivery",
  //         },
  //       ],
  //     },
  //   },
  //   search: null,
  //   deliveryPastDue: false,
  //   pickupPastDue: false,
  //   deliverToday: false,
  //   pickupToday: false,
  //   bolNeeded: false,
  //   website: "acv",
  // },
  // {
  //   comments: "",
  //   createdDate: "2025-02-11T10:12:23.950Z",
  //   destinationCity: "Manhiem",
  //   destinationState: "PA",
  //   hasBidsAvailable: false,
  //   hasEnclosedTrailer: false,
  //   hasInopVehicle: false,
  //   id: "20303292",
  //   mileage: "108",
  //   name: "deff",
  //   numberOfCars: "1",
  //   originCity: "BARTONSVILLE",
  //   originState: "PA",
  //   photoURL: "",
  //   pricePerMile: "$1.62",
  //   pricePerShipment: "$175",
  //   sortingDate: {},
  //   viewLink:
  //     "/tab/Transport/ViewLoadShort.asp?nload_id=20303292&npickup_code=",
  //   website: "carsarrive",
  //   yearMakeModel: "2016 Ford Focus",
  // },
  // {
  //   comments: "",
  //   createdDate: "2025-02-11T10:12:23.950Z",
  //   destinationCity: "Wexford",
  //   destinationState: "PA",
  //   hasBidsAvailable: false,
  //   hasEnclosedTrailer: false,
  //   hasInopVehicle: false,
  //   id: "20301082",
  //   mileage: "70",
  //   name: "deff",
  //   numberOfCars: "1",
  //   originCity: "Franklin",
  //   originState: "PA",
  //   photoURL: "",
  //   pricePerMile: "$2.86",
  //   pricePerShipment: "$200",
  //   sortingDate: {},
  //   viewLink:
  //     "/tab/Transport/ViewLoadShort.asp?nload_id=20301082&npickup_code=",
  //   website: "carsarrive",
  //   yearMakeModel: "2021 Honda CR-V",
  // },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.951Z",
  //     destinationCity: "Saint James",
  //     destinationState: "NY",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20277891",
  //     mileage: "179",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Wilkes-Barre",
  //     originState: "PA",
  //     photoURL:
  //       "https://adesa.kar-media.com/display.php?img=760471766_0_20250127064442983.jpg",
  //     pricePerMile: "$1.73",
  //     pricePerShipment: "$310",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20277891&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2022 GENESIS G70 2.0T AWD",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.952Z",
  //     destinationCity: "Dulles",
  //     destinationState: "VA",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20281945",
  //     mileage: "124",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Wrightsville",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$1.85",
  //     pricePerShipment: "$230",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20281945&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2018 CHEVROLET BOLT EV",
  //   },
  //   {
  //     comments: "INOP w/o keys",
  //     createdDate: "2025-02-11T10:12:23.952Z",
  //     destinationCity: "Dulles",
  //     destinationState: "VA",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20290233",
  //     mileage: "124",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Wrightsville",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$2.18",
  //     pricePerShipment: "$270",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20290233&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2008 CHEVROLET G3500 CARGO 4X2",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.952Z",
  //     destinationCity: "JERICHO",
  //     destinationState: "NY",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20296151",
  //     mileage: "146",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "LIMERICK",
  //     originState: "PA",
  //     photoURL:
  //       "https://adesa.kar-media.com/display.php?img=769258078_1_20250131063701019.jpg",
  //     pricePerMile: "$1.92",
  //     pricePerShipment: "$280",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20296151&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2022 Ram 1500 4WD Crew Cab Big Horn 5.7L 8cyl eTor",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.952Z",
  //     destinationCity: "OIL CITY",
  //     destinationState: "PA",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20296920",
  //     mileage: "44",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Conneaut Lake",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$4.09",
  //     pricePerShipment: "$180",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20296920&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2014 Chevrolet Silverado 1500",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.953Z",
  //     destinationCity: "North Huntingdon",
  //     destinationState: "PA",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20297666",
  //     mileage: "145",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Fairview",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$1.97",
  //     pricePerShipment: "$285",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20297666&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2022 Hyundai Tucson",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.953Z",
  //     destinationCity: "MCCLELLANDTOWN",
  //     destinationState: "PA",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20307395",
  //     mileage: "221",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "MANHEIM",
  //     originState: "PA",
  //     photoURL:
  //       "https://adesa.kar-media.com/display.php?img=1016208236_0_20250124134528122.jpg",
  //     pricePerMile: "$1.22",
  //     pricePerShipment: "$270",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20307395&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2024 Chevrolet SILVERADO 1500 4WD CREW CAB LT TRAI",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.953Z",
  //     destinationCity: "Palmyra",
  //     destinationState: "NJ",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20308341",
  //     mileage: "24",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "CONSHOHOCKEN",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$4.79",
  //     pricePerShipment: "$115",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20308341&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2016 Kia Sedona",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.953Z",
  //     destinationCity: "WHITE HALL",
  //     destinationState: "WV",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20311912",
  //     mileage: "125",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Bedford",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$2.04",
  //     pricePerShipment: "$255",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20311912&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2018 Chevrolet Silverado 1500",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.953Z",
  //     destinationCity: "lake hopatcong",
  //     destinationState: "NJ",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20312705",
  //     mileage: "87",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Lansdale",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$1.55",
  //     pricePerShipment: "$135",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20312705&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2017 Mazda Mazda6 2017.5",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.953Z",
  //     destinationCity: "Pleasantville",
  //     destinationState: "NJ",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20313267",
  //     mileage: "167",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Wilkes Barre",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$0.83",
  //     pricePerShipment: "$139",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20313267&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2022 Nissan Altima",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.954Z",
  //     destinationCity: "Copiague",
  //     destinationState: "NY",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20313243",
  //     mileage: "173",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Reading",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$1.24",
  //     pricePerShipment: "$215",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20313243&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2022 BMW X5",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.954Z",
  //     destinationCity: "Parsippany",
  //     destinationState: "NJ",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20314281",
  //     mileage: "314",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Mt Pleasant",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$1.04",
  //     pricePerShipment: "$325",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20314281&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2012 Chevrolet Silverado 1500",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.954Z",
  //     destinationCity: "Tulsa",
  //     destinationState: "OK",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20308415",
  //     mileage: "975",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "McMurray",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$0.69",
  //     pricePerShipment: "$675",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20308415&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2016 Jeep Wrangler",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.954Z",
  //     destinationCity: "Hot Springs",
  //     destinationState: "AR",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20308943",
  //     mileage: "1207",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Quakertown",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$0.58",
  //     pricePerShipment: "$700",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20308943&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2009 Chevrolet Silverado 1500",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.954Z",
  //     destinationCity: "KANSAS CITY",
  //     destinationState: "MO",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20308039",
  //     mileage: "1114",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Quakertown",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$0.49",
  //     pricePerShipment: "$550",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20308039&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2023 Chevrolet Corvette",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.954Z",
  //     destinationCity: "San Angelo",
  //     destinationState: "TX",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20306171",
  //     mileage: "1679",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Manheim",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$0.61",
  //     pricePerShipment: "$1,030",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20306171&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2023 Ram Pickup 1500",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.955Z",
  //     destinationCity: "little rock",
  //     destinationState: "AR",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20299518",
  //     mileage: "1123",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "POTTSVILLE",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$0.76",
  //     pricePerShipment: "$850",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20299518&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2013 Ford F150",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.955Z",
  //     destinationCity: "ST. CLOUD",
  //     destinationState: "FL",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20288664",
  //     mileage: "1045",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "ALTOONA",
  //     originState: "PA",
  //     photoURL:
  //       "https://adesa.kar-media.com/display.php?img=967972895_208_20250117091145093.jpg",
  //     pricePerMile: "$0.89",
  //     pricePerShipment: "$925",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20288664&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2022 FORD F-150 SUPER CREW STYLESIDE 4X4 XLT OXFOR",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.955Z",
  //     destinationCity: "Kingsport",
  //     destinationState: "TN",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20301996",
  //     mileage: "524",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Allentown",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$0.82",
  //     pricePerShipment: "$430",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20301996&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2020 Honda Odyssey",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.955Z",
  //     destinationCity: "Kodak",
  //     destinationState: "TN",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20304580",
  //     mileage: "451",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Mt Pleasant",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$1.08",
  //     pricePerShipment: "$485",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20304580&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2016 Toyota 4runner",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.955Z",
  //     destinationCity: "Clinton",
  //     destinationState: "MS",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20305360",
  //     mileage: "1141",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Jenkintown",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$0.61",
  //     pricePerShipment: "$700",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20305360&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2020 Toyota Corolla",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.955Z",
  //     destinationCity: "FORT PAYNE",
  //     destinationState: "AL",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20308175",
  //     mileage: "690",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "lyndora",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$0.87",
  //     pricePerShipment: "$600",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20308175&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2023 Hyundai Elantra",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.955Z",
  //     destinationCity: "Morristown",
  //     destinationState: "TN",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20308361",
  //     mileage: "480",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Johnstown",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$0.96",
  //     pricePerShipment: "$460",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20308361&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2018 Jeep Renegade",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.955Z",
  //     destinationCity: "Sanford",
  //     destinationState: "NC",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20311910",
  //     mileage: "408",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Manchester",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$0.96",
  //     pricePerShipment: "$390",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20311910&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2008 Gmc Sierra 2500",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.955Z",
  //     destinationCity: "Knoxville",
  //     destinationState: "TN",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20312568",
  //     mileage: "561",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Manchester",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$0.82",
  //     pricePerShipment: "$460",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20312568&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2016 Cadillac Escalade",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.955Z",
  //     destinationCity: "Clarksville",
  //     destinationState: "TN",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20313244",
  //     mileage: "602",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Kittanning",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$0.97",
  //     pricePerShipment: "$585",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20313244&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2022 Buick Enclave",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.956Z",
  //     destinationCity: "Athens",
  //     destinationState: "TN",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20313172",
  //     mileage: "674",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Allentown",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$0.62",
  //     pricePerShipment: "$420",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20313172&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2013 Honda Civic",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.956Z",
  //     destinationCity: "Fayetteville",
  //     destinationState: "NC",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20314214",
  //     mileage: "544",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "LARKSVILLE",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$0.68",
  //     pricePerShipment: "$370",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20314214&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2020 Nissan Altima",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.956Z",
  //     destinationCity: "Bourbonnais",
  //     destinationState: "IL",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20313311",
  //     mileage: "502",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Kittanning",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$0.81",
  //     pricePerShipment: "$405",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20313311&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2023 Buick Encore gx",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.956Z",
  //     destinationCity: "DEFIANCE",
  //     destinationState: "OH",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20313789",
  //     mileage: "290",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Monroeville",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$0.93",
  //     pricePerShipment: "$270",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20313789&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2016 Buick Encore",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.956Z",
  //     destinationCity: "COLLINSVILLE",
  //     destinationState: "IL",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20313978",
  //     mileage: "871",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Ambler",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$0.56",
  //     pricePerShipment: "$490",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20313978&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2014 Ford Escape",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.956Z",
  //     destinationCity: "Ottawa",
  //     destinationState: "IL",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20313067",
  //     mileage: "604",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Windber",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$0.81",
  //     pricePerShipment: "$490",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20313067&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2014 Ram 1500",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.956Z",
  //     destinationCity: "Tipton",
  //     destinationState: "IN",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20313114",
  //     mileage: "435",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Johnstown",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$0.92",
  //     pricePerShipment: "$400",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20313114&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2016 Chevrolet Silverado 1500",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.956Z",
  //     destinationCity: "WICKLIFFE",
  //     destinationState: "OH",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20313150",
  //     mileage: "140",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "PITTSBURGH",
  //     originState: "PA",
  //     photoURL:
  //       "https://adesa.kar-media.com/display.php?img=989593665_642_20250203144657075.jpg",
  //     pricePerMile: "$1.21",
  //     pricePerShipment: "$170",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20313150&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2022 FORD EDGE AWD-SEL INFINITE BLACK/AGATE BLACK",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.957Z",
  //     destinationCity: "Marion",
  //     destinationState: "IA",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20312436",
  //     mileage: "968",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Exton",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$0.51",
  //     pricePerShipment: "$490",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20312436&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2017 Volkswagen Golf",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.957Z",
  //     destinationCity: "CENTERVILLE",
  //     destinationState: "OH",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20310935",
  //     mileage: "549",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "HATFIELD",
  //     originState: "PA",
  //     photoURL:
  //       "https://adesa.kar-media.com/display.php?img=781824883_1_20250206135616209.jpg",
  //     pricePerMile: "$0.66",
  //     pricePerShipment: "$365",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20310935&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2022 Ram 1500 4WD Crew Cab Big Horn 5.7L 8cyl DIAM",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.957Z",
  //     destinationCity: "Anderson",
  //     destinationState: "IN",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20311808",
  //     mileage: "342",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "BELLE VERNON",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$1.07",
  //     pricePerShipment: "$365",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20311808&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2016 Ram 1500",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.957Z",
  //     destinationCity: "ST. LOUIS PARK",
  //     destinationState: "MN",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20308587",
  //     mileage: "1162",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "NEWTOWN SQUARE",
  //     originState: "PA",
  //     photoURL:
  //       "https://adesa.kar-media.com/display.php?img=760030451_0_20250207103051231.jpg",
  //     pricePerMile: "$0.58",
  //     pricePerShipment: "$675",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20308587&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2022 SUBARU FORESTER Limited RED",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.957Z",
  //     destinationCity: "Ashland",
  //     destinationState: "OH",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20293076",
  //     mileage: "202",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "BELLE VERNON",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$1.24",
  //     pricePerShipment: "$250",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20293076&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2018 Chevrolet Cruze",
  //   },
  //   {
  //     comments: "INOP w/keys",
  //     createdDate: "2025-02-11T10:12:23.957Z",
  //     destinationCity: "Franklin",
  //     destinationState: "OH",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: true,
  //     id: "20299468",
  //     mileage: "265",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "NEW EAGLE",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$1.40",
  //     pricePerShipment: "$370",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20299468&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2021 NISSAN FRONTIER",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.957Z",
  //     destinationCity: "Quincy",
  //     destinationState: "IL",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20299551",
  //     mileage: "965",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Colmar",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$0.57",
  //     pricePerShipment: "$550",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20299551&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2014 Ford Taurus",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.958Z",
  //     destinationCity: "Columbiana",
  //     destinationState: "OH",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20299892",
  //     mileage: "100",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "GIRARD",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$2.45",
  //     pricePerShipment: "$245",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20299892&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2021 Ford Escape",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.958Z",
  //     destinationCity: "Rhinelander",
  //     destinationState: "WI",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20301720",
  //     mileage: "1025",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Manheim",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$0.76",
  //     pricePerShipment: "$775",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20301720&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2021 Cadillac XT5",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.958Z",
  //     destinationCity: "PARMA",
  //     destinationState: "OH",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20303906",
  //     mileage: "108",
  //     name: "deff",
  //     numberOfCars: "2",
  //     originCity: "ERIE",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$1.62",
  //     pricePerShipment: "$175",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20303906&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2015 Ford Fusion",
  //   },
  //   {
  //     comments: "",
  //     createdDate: "2025-02-11T10:12:23.958Z",
  //     destinationCity: "INDIANAPOLIS",
  //     destinationState: "IN",
  //     hasBidsAvailable: false,
  //     hasEnclosedTrailer: false,
  //     hasInopVehicle: false,
  //     id: "20304118",
  //     mileage: "370",
  //     name: "deff",
  //     numberOfCars: "1",
  //     originCity: "Mercer",
  //     originState: "PA",
  //     photoURL: "",
  //     pricePerMile: "$1.07",
  //     pricePerShipment: "$395",
  //     sortingDate: {},
  //     viewLink:
  //       "/tab/Transport/ViewLoadShort.asp?nload_id=20304118&npickup_code=",
  //     website: "carsarrive",
  //     yearMakeModel: "2018 TESLA MODEL 3 LONG RANGE BATTERY AWD",
  //   },
];
